[package]
name = "oauth_client"
version = "0.1.1"
authors = ["yzhu <Yanhao.Zhu@am.sony.com>"]

[dependencies]
roadrunner = "0.1.1"
hyper = "0.11"
serde="1.0"
serde_json = "1.0"
serde_derive="1.0"
log = "0.3.7"
env_logger = "0.4.2"
tokio-core = "0.1.6"
